// <auto-generated />
using System;
using HealthMetrics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthMetrics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthMetricsDbContext))]
    [Migration("20260812004600_AddEstimatedAlcoholEstimate")]
    partial class AddEstimatedAlcoholEstimate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HealthMetrics.Application.Models.DailyMetricSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Acwr")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CarbohydratesGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CardioLoad")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConsumedCaloriesKcal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DailyVo2MaxMlKgMin")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeepSleepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedAlcoholGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FatGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HrvRmssdMilliseconds")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MetricDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProteinGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemSleepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestingHeartRateBpm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RunVo2MaxMlKgMin")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SleepEfficiency")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetLoad")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey", "MetricDate")
                        .IsUnique();

                    b.ToTable("daily_metric_snapshots", (string)null);
                });

            modelBuilder.Entity("HealthMetrics.Application.Models.HealthConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey")
                        .IsUnique();

                    b.ToTable("health_connections", (string)null);
                });

            modelBuilder.Entity("HealthMetrics.Application.Models.SyncHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersistedDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey", "StartedAtUtc");

                    b.ToTable("sync_history", (string)null);
                });

            modelBuilder.Entity("HealthMetrics.Application.Models.UserDataOwnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey")
                        .IsUnique();

                    b.ToTable("user_data_ownership", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
