// <auto-generated />
using System;
using FitbitMetrics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitbitMetrics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FitbitDbContext))]
    [Migration("20260719011405_AddSyncHistory")]
    partial class AddSyncHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FitbitMetrics.Application.Models.DailyMetricSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CalciumMilligrams")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CarbohydratesGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConsumedCaloriesKcal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FatGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FiberGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HrvRmssdMilliseconds")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IronMilligrams")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MetricDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PotassiumMilligrams")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProteinGrams")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RestingHeartRateBpm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SodiumMilligrams")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Vo2MaxMlKgMin")
                        .HasPrecision(9, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey", "MetricDate")
                        .IsUnique();

                    b.ToTable("daily_metric_snapshots", (string)null);
                });

            modelBuilder.Entity("FitbitMetrics.Application.Models.FitbitConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FitbitUserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey")
                        .IsUnique();

                    b.ToTable("fitbit_connections", (string)null);
                });

            modelBuilder.Entity("FitbitMetrics.Application.Models.SyncHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersistedDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserKey", "StartedAtUtc");

                    b.ToTable("sync_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
